image: node:20
stages: [deploy]

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - FE/**
        - .gitlab-ci.yml
    - when: never

cache:
  key: npm-fe
  paths:
    - FE/.npm/

pages:
  tags: ["fe-pages-docker"]
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - FE/**
        - .gitlab-ci.yml
      when: on_success
    - when: never
  script:
    - npm ci --prefix FE --cache FE/.npm --prefer-offline
    - npm run build --prefix FE
    - rm -rf public
    - mv FE/dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
    expire_in: 1 week
