listening-port=3478

listening-ip=172.31.16.218
relay-ip=172.31.16.218
external-ip=43.202.157.94/172.31.16.218

realm=hairapply.local
server-name=hairapply-turn
fingerprint
lt-cred-mech
user=hairapply:hairapply-turn-change-this-2026

min-port=49160
max-port=49200

no-tls
no-dtls
no-cli
simple-log
log-file=stdout
pidfile=/tmp/hairapply-turnserver.pid
