listening-port=3478

listening-ip=172.31.55.186
relay-ip=172.31.55.186
external-ip=43.203.152.0/172.31.55.186

realm=hairapply.local
server-name=hairapply-turn
fingerprint
lt-cred-mech
user=hairapply:hairapply-turn-change-this-2026

min-port=49160
max-port=49200

no-tls
no-dtls
no-cli
simple-log
log-file=stdout
pidfile=/tmp/hairapply-turnserver.pid
